### ISSUE TITLE
Remove use_fates, use_cndv, fates options, and other options not used

### ISSUE THREAD

**Issue by slevisconsulting** [ESCOMP/SimpleLand#44]
Self explanatory from the title. I'm opening this issue to keep track of options to remove that are not listed in the title.

use_lai_streams
use_dynroot
single_column (KEEP)

**Comment by ekluzek** [comment]
Thanks for that @slevisconsulting. One note is that single_column is one option that might be good to leave around, since I could see where it could be useful in the future. The other options have no reason to stay around and should be removed though...

**Comment by ekluzek** [comment]
The above comment relates to #29

**Comment by slevisconsulting** [comment]
I would like confirmation on whether to keep/remove several other options. Please put a YES, NO, MAYBE next to each:
use_hydrstress
use_luna
use_fun
use_lch4
use_nitrif_denitrif
use_vertsoilc
use_century_decomp
use_mimics_decomp
use_flexibleCN
use_bedrock
use_fertilizer
use_crop
use_grainproduct
use_c13_timeseries
use_c13
use_c14
use_c14_bombspike
use_ozone
use_vichydro
use_snicar_frc
use_vancouver
use_mexicocity
use_extralakelayers
use_nguardrail

**Comment by ekluzek** [comment]
@slevisconsulting all of those are things to remove. The tricky thing is because of dependencies they end up being harder to remove than we'd like.

One way to look at it is to look in mml_main and see what's used in there. Another way is to see what's used in clm_driver. There is a use of use_cn in clm_driver right now that means that we can't get rid of it straight away. But, eventually use_cn is something that should be removed as well.

I think you should be able to remove all of the above reasonably well. The logic for use_crop might make it harder to remove, but others should be OK.

So in this entire list, of variables the only one to keep around is the single_column option. It's not currently functional, but eventually it would be helpful for it to be.

**Comment by slevisconsulting** [comment]
While waiting for a test, I executed the command `git ls-files | xargs wc -l` and got just over 59000 lines.

**Comment by slevisconsulting** [comment]
The cheyenne gnu ERS test that I've been using has been failing occasionally.
@ekluzek and @fischer-ncar suggested running on more nodes to gain access to more memory.

In config_pes.xml I changed ntasks from -10 to -20. I ran twice and the first time failed. I also tried -12 once and it completed. However, both -20 and -12 changed answers from -10. I never remember whether that should be expected...

Regardless, I'm going back to -10 for now.

**Comment by ekluzek** [comment]
@slevisconsulting I think cases with CAM and CICE are expected to change answers on different task count, because of CICE. So we probably need to figure out the appropriate task count and redo the baselines over again with just that change. That update should go to the main branch.
