### ISSUE TITLE
Add a tool for modifying SLIM mml_surdat files

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/SimpleLand#55]
It would be useful to have a tool that can modify SLIM mml_surdat files. We think this could be modified from the fsurdat_modifier tool in CTSM. Since, there likely won't be very many tools in the SLIM distribution it probably makes sense to just make a subdirectory called "tools" and put this tool in there. @slevisconsulting is the natural person to work on this since he worked on the CTSM tool. It's likely there wouldn't need to be many differences from the CTSM version, just maybe the assumption of variable names on the file.

This is a pretty important task for making SLIM a usable tool for public use.

**Comment by slevisconsulting** [comment]
Related work:
- In #65 I wrote a simple matlab script to extract an mml_surdat file from a higher resolution to a lower resolution (tested f19 to f45 and f10). By "extract" I really just mean that I pull out the section of the higher res grid that fits the size of the lower res grid without regard to realism. With the same matlab file we could add metadata to the low-res files, as raised in #36.
- #36 will also need to be addressed in this issue here (#55).

**Comment by ekluzek** [comment]
This was completed.
